name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Setup MongoDB
      uses: docker://mongo:latest
      with:
        ports: 27017:27017

    - name: Build and deploy
      run: npm run build

    - name: Start server
      run: node server.js
